"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-yp2*luom0!lf_p&m4_eqyhwxsqg8*clod^347miu4u-o0ic80k'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    
    #'grappelli', #biblioteca p/ mudar interface do site, saiu do padrão inicial django 
    #comentar grappelli para poder usar outra biblioteca de interface
    
    'jazzmin',
    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

   # 'products',
   'livros',
   
]

#GRAPPELLI_ADMIN_TITLE = 'Libreasy' #colocar Libreasy como titulo de cima

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  # Diretório onde os arquivos estáticos serão coletados
STATICFILES_DIRS = [BASE_DIR / 'static']  # Caso tenha uma pasta static na raiz do seu projeto

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configurações da biblioteca jazzmin para estilizar o site


JAZZMIN_SETTINGS = {
    'site_title': 'Libreasy',
    'site_header': 'Libreasy',
    'site_brand': 'Libreasy',
    'site_logo': 'images/Libreasy_logo2.png',  # Caminho do logo dentro da pasta static
    #'login_logo': 'images/Libreasy_logo.jpg',  # Logo usado na tela de login
    'custom_css': 'css/custom.css',  # Adicione esta linha para carregar o CSS customizado
    
    
    'icons': {
        'auth': 'fas fa-users-cog',
        'auth.user': 'fas fa-user',
        'auth.Group': 'fas fa-users',
        #'products.Brand': 'fas fa-copyright',
        #'products.Category': 'fas fa-object-group',
        #'products.Product': 'fas fa-box',
        'livros.Editora': 'fa-brands fa-etsy',
        #'livros.Genero': 'fa-solid fa-book-open',
        'livros.Gênero': 'fa-solid fa-bookmark',
        'livros.Livro': 'fa-solid fa-book-open',
        'livros.Autor': 'fa-solid fa-book-open',
    },
    

    'welcome_sign': 'Bem-vindo(a) ao Libreasy',
    'copyright': 'PycodeBR LTDA',
    #'search_model': ['product.Product'],
    'search_model': ['livro.Livro'],
    'show_ui_builder': True,
}

# LOGIN_URL = "/admin/login/"  # Caminho para a página de login
# LOGIN_REDIRECT_URL = "/"  # Para onde redirecionar após login bem-sucedido
# LOGOUT_REDIRECT_URL = "/admin/login/"  # Para onde redirecionar após logout

#<i class="fa-solid fa-bookmark"></i>
