# Generated by Django 5.0 on 2025-05-14 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Autor',
                'db_table': 'autor',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Editora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Editora',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Gênero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Gênero',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('isbn', models.IntegerField(unique=True, verbose_name='ISBN')),
                ('serie', models.CharField(blank=True, default='', max_length=50, verbose_name='Série')),
                ('edicao', models.IntegerField(default=1, verbose_name='Edição')),
                ('volume', models.IntegerField(default=1, verbose_name='Volume')),
                ('capa_url', models.URLField(blank=True, help_text='URL completa da imagem (ex: https://exemplo.com/imagem.png)', max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='livros', to='livros.autor', verbose_name='Autor')),
                ('editora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='livros', to='livros.editora', verbose_name='Editora')),
                ('gênero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='livros', to='livros.gênero', verbose_name='Gênero')),
            ],
            options={
                'verbose_name': 'Livro',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Copia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tombamento', models.CharField(max_length=50, unique=True, verbose_name='Tombamento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('status', models.CharField(choices=[('EMPRESTADO', 'Emprestado'), ('DISPONIVEL', 'Disponível')], default='DISPONIVEL', max_length=20, verbose_name='Situação')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='copias', to='livros.livro', verbose_name='Livro')),
            ],
            options={
                'verbose_name': 'Copia',
                'ordering': ['tombamento'],
            },
        ),
    ]
