# Generated by Django 5.0 on 2025-02-17 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Brand',
            new_name='Autor',
        ),
        migrations.AlterModelOptions(
            name='autor',
            options={'ordering': ['name'], 'verbose_name': 'Autor'},
        ),
    ]
