# Generated by Django 5.0 on 2025-05-09 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editora',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='gênero',
            name='is_active',
        ),
    ]
