# Generated by Django 5.0 on 2025-05-15 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'ordering': ['name'], 'verbose_name': 'Autor', 'verbose_name_plural': 'Autores'},
        ),
    ]
