# Generated by Django 5.0 on 2025-02-17 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0002_rename_brand_autor_alter_autor_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='autor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='livros', to='livros.autor', verbose_name='Autor'),
            preserve_default=False,
        ),
    ]
