# Generated by Django 5.0 on 2025-05-23 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0002_alter_autor_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='isbn',
            field=models.CharField(max_length=30, unique=True, verbose_name='ISBN'),
        ),
    ]
