# Generated by Django 5.0 on 2025-05-14 17:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('livros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Empréstimo')),
                ('data_devolucao', models.DateField(verbose_name='Prazo de Devolução')),
                ('data_devolucao_real', models.DateField(blank=True, null=True, verbose_name='Data de Devolução')),
                ('status', models.CharField(choices=[('EMPRESTADO', 'Emprestado'), ('EM_ATRASO', 'Em Atraso'), ('DEVOLVIDO', 'Devolvido')], default='EMPRESTADO', max_length=20, verbose_name='Situação')),
                ('copia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='livros.copia', verbose_name='Tombamento/Livro/ISBN:')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Empréstimo',
                'verbose_name_plural': 'Empréstimos',
                'ordering': ['-data_emprestimo'],
            },
        ),
    ]
