# Generated by Django 5.0 on 2025-04-17 19:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('livros', '0004_livro_capa_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copia_id', models.CharField(help_text='Identificador único da cópia física', max_length=50, verbose_name='ID da Cópia')),
                ('data_emprestimo', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Empréstimo')),
                ('data_devolucao', models.DateField(verbose_name='Data de Devolução')),
                ('data_devolucao_real', models.DateField(blank=True, null=True, verbose_name='Data Real de Devolução')),
                ('status', models.CharField(choices=[('EMPRESTADO', 'Emprestado'), ('EM_ATRASO', 'Em atraso'), ('DEVOLVIDO', 'Devolvido')], default='EMPRESTADO', max_length=20, verbose_name='Status')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='livros.livro', verbose_name='Livro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Empréstimo',
                'verbose_name_plural': 'Empréstimos',
                'ordering': ['-data_emprestimo'],
            },
        ),
    ]
